### ISSUE TITLE
[Spark][Bug]: NPE exception when execute `create table like ` command without using arctic.

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/arctic#1210]
### What happened?

execute sql

```
create table if not exists tmp.bdm_sql_test like tmp.bdm_transfer_info
```

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

Spark

### Relevant log output

```shell
2023-03-09 17:41:46 CST SparkTableLineageListener WARN - Action 'command' execution failed
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at com.netease.arctic.spark.sql.execution.ExtendedArcticStrategy.apply(ExtendedArcticStrategy.scala:56)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:63)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:67)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:78)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:162)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:160)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1429)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@hellojinsilei Could you please add the cause information of this Bug before fixing it?

**Comment by hellojinsilei** [comment]
This problem is caused by our code logic did not make a judgment on the empty provider in RewriteArcticCommand.

Desired effect:
1. In ArcticSparkSessionCataog, provider = 'arctic' can create the arctic table
2. In ArcticSparkCatalog, the provider must be arctic or None. If it is None, the default value is arctic

**Comment by baiyangtx** [comment]
> @hellojinsilei Could you please add the cause information of this Bug before fixing it?

In `RewriteArcticCommand` rule, the code check the provider by `provider.get != null && provider.get.equals('arctic') ` 

The optional.get always return non-null object or throw a exception.
