### ISSUE TITLE
[Bug]: When the optimize task commits, if mysql is disconnected, the task will be abnormal.

### ISSUE THREAD

**Issue by ShawHee** [NetEase/arctic#1245]
### What happened?

![image](https://user-images.githubusercontent.com/28854922/225807240-f8cfeab1-1be9-493b-80f0-415b525b68d5.png)
All optimize_task statuses are "prepared", no commit has been made and will not fail.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. The optimize task is in the prepared state, ready to commit.
```
 boolean committed = optimizeCommit.commit(tableOptimizeRuntime.getCurrentSnapshotId());
        if (committed) {
          commitTime = System.currentTimeMillis();
          optimizeTasksCommitted(optimizeCommit, commitTime);
        }
```
3. When the commit program executes to TableOptimizeItem.optimizeTasksCommitted(), Mysql connection disconnected.
4. At this time, writing data is unsuccessful, and the rollback also fails, and an exception will be thrown.
5. OptimizeCommitWorker.java: 
```
catch (Throwable t) {
          LOG.error("{} {} unexpected commit error ", workerName, currentTable, t);
```
6. After that, execute the tableOptimize.tryTriggerCommit() method. Because the status of optimizeTasks in the program is "commited", it will not commit again. 
![image](https://user-images.githubusercontent.com/28854922/225808702-a9428b3d-f69c-4ccd-a999-80f173a45c1f.png)
```
public void tryTriggerCommit() {
    tasksLock.lock();
    try {
      if (waitCommit.get()) {
        return;
      }
      if (!allTasksPrepared()) {
        return;
      }
      boolean success = ServiceContainer.getOptimizeService().triggerOptimizeCommit(this);
      if (success) {
        waitCommit.set(true);
      }
    } finally {
      tasksLock.unlock();
    }
  }
```

### Relevant log output

```shell
2023-03-13 05:12:59,262 WARN [Metastore Scheduled Commit Worker 0] [com.netease.arctic.ams.server.optimize.TableOptimizeItem] [] - failed to persist optimize history after commit, ignore. arctic_da_market.da_market.arctic_dwd_live_att_lesson
org.apache.ibatis.exceptions.PersistenceException:
### Error updating database.  Cause: java.sql.SQLException: Connection com.mysql.jdbc.JDBC4Connection@654c32ee is closed.
### The error may exist in com/netease/arctic/ams/server/mapper/OptimizeHistoryMapper.java (best guess)
### The error may involve com.netease.arctic.ams.server.mapper.OptimizeHistoryMapper.insertOptimizeHistory
### The error occurred while executing an update
### SQL: insert into optimize_history (catalog_name, db_name, table_name, optimize_range, optimize_type,visible_time, commit_time, plan_time, duration, total_file_cnt_before, total_file_size_before, insert_file_cnt_before, insert_file_size_before, delete_file_cnt_before, delete_file_size_before, base_file_cnt_before, base_file_size_before, pos_delete_file_cnt_before, pos_delete_file_size_before, total_file_cnt_after,total_file_size_after,snapshot_id, total_size,added_files, removed_files, added_records, removed_records, added_files_size, removed_files_size, total_files, total_records, partition_cnt, partitions, max_change_transaction_id) values (?, ?, ?, ?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
### Cause: java.sql.SQLException: Connection com.mysql.jdbc.JDBC4Connection@654c32ee is closed.
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85) ~[mybatis-3.5.5.jar:3.5.5]
        at com.sun.proxy.$Proxy208.insertOptimizeHistory(Unknown Source) ~[?:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.optimizeTasksCommitted(TableOptimizeItem.java:620) [arctic-ams-server-0.3.2-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.commitOptimizeTasks(TableOptimizeItem.java:837) [arctic-ams-server-0.3.2-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCommitWorker.run(OptimizeCommitWorker.java:50) [arctic-ams-server-0.3.2-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.sql.SQLException: Connection com.mysql.jdbc.JDBC4Connection@654c32ee is closed.
        at org.apache.commons.dbcp2.DelegatingConnection.checkOpen(DelegatingConnection.java:605) ~[commons-dbcp2-2.7.0.jar:2.7.0]
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:300) ~[commons-dbcp2-2.7.0.jar:2.7.0]
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:303) ~[commons-dbcp2-2.7.0.jar:2.7.0]
        at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
        at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55) ~[mybatis-3.5.5.jar:3.5.5]
        at com.sun.proxy.$Proxy130.prepareStatement(Unknown Source) ~[?:?]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:87) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197) ~[mybatis-3.5.5.jar:3.5.5]
        ... 15 more
2023-03-13 05:12:59,268 ERROR [Metastore Scheduled Commit Worker 0] [com.netease.arctic.ams.server.optimize.OptimizeCommitWorker] [] - Optimize Committer Worker-0 com.netease.arctic.ams.server.optimize.TableOptimizeItem@7ccdc1ba unexpected commit error
org.apache.ibatis.exceptions.PersistenceException:
### Error rolling back transaction.  Cause: java.sql.SQLException: Connection com.mysql.jdbc.JDBC4Connection@654c32ee is closed.
### Cause: java.sql.SQLException: Connection com.mysql.jdbc.JDBC4Connection@654c32ee is closed.
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.rollback(DefaultSqlSession.java:243) ~[mybatis-3.5.5.jar:3.5.5]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.optimizeTasksCommitted(TableOptimizeItem.java:623) ~[arctic-ams-server-0.3.2-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.commitOptimizeTasks(TableOptimizeItem.java:837) ~[arctic-ams-server-0.3.2-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCommitWorker.run(OptimizeCommitWorker.java:50) [arctic-ams-server-0.3.2-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.sql.SQLException: Connection com.mysql.jdbc.JDBC4Connection@654c32ee is closed.
        at org.apache.commons.dbcp2.DelegatingConnection.checkOpen(DelegatingConnection.java:605) ~[commons-dbcp2-2.7.0.jar:2.7.0]
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:482) ~[commons-dbcp2-2.7.0.jar:2.7.0]
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:484) ~[commons-dbcp2-2.7.0.jar:2.7.0]
        at org.apache.ibatis.transaction.jdbc.JdbcTransaction.rollback(JdbcTransaction.java:82) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.executor.BaseExecutor.rollback(BaseExecutor.java:256) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.executor.CachingExecutor.rollback(CachingExecutor.java:126) ~[mybatis-3.5.5.jar:3.5.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.rollback(DefaultSqlSession.java:240) ~[mybatis-3.5.5.jar:3.5.5]
        ... 10 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aireed** [comment]
cc @wangtaohz ,  do you have a same issue  in process?

**Comment by wangtaohz** [comment]
OK, I will follow the PR.
