### ISSUE TITLE
[Bug]: TreeNode has already been completed when open upsert mode and use insert into in Spark

### ISSUE THREAD

**Issue by HuangFru** [NetEase/arctic#1265]
### What happened?

I am doing a performance test of spark upsert mode in the Arctic.
I have a table like this:
```
create table lineitem_upsert_41 (
   l_orderkey bigint,
   l_partkey bigint,
   l_suppkey bigint,
   l_linenumber int,
   l_quantity double,
   l_extendedprice double,
   l_discount double,
   l_tax double,
   l_returnflag string,
   l_linestatus string,
   l_shipdate date,
   l_receiptdate date,
   l_shipinstruct string,
   l_shipmode string,
   l_comment string,
   l_commitdate date,
   PRIMARY KEY (l_orderkey,l_linenumber)
) USING arctic PARTITIONED BY (l_commitdate) tblproperties (
	"write.upsert.enabled"="true",
  "base.file-index.hash-bucket"="4"
);
```
This is a TPCH table, and I set these session properties:
```
set `spark.sql.arctic.check-source-data-uniqueness.enabled`=`true`
set `spark.sql.arctic.optimize-write-enabled`=`true`
```

First, I insert overwrite some data(sf100 in TPCH, about 15GB) into the table.The SQL is :
```
insert overwrite table lineitem_upsert_41 select nvl(l_orderkey,0),l_partkey,l_suppkey,nvl(l_linenumber,0),l_quantity,l_extendedprice,l_discount,l_tax,l_returnflag,l_linestatus,l_shipdate,l_receiptdate,l_shipinstruct,l_shipmode,l_comment,l_commitdate from spark_catalog.test_origin.lineitem_sf100;
```
Insert overwrite works fine. And when I insert into some data(sf1, about 150 MB) the table use SQL:
```
insert into table lineitem_upsert_41 select nvl(l_orderkey,0),l_partkey,l_suppkey,nvl(l_linenumber,0),l_quantity,l_extendedprice,l_discount,l_tax,l_returnflag,l_linestatus,l_shipdate,l_receiptdate,l_shipinstruct,l_shipmode,l_comment,l_commitdate from spark_catalog.test_origin.lineitem_sf1;
```
I will get the error.
```
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2303)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2252)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2251)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2251)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1124)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1124)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1124)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2490)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2432)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2421)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:902)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
	at com.netease.arctic.shade.org.apache.spark.sql.execution.datasources.v2.ArcticTableWriteExec.writeInsert(ArcticTableWriteExec.scala:78)
	... 31 more
Caused by: java.lang.IllegalStateException: The write key [[8075] TreeNode(3,3)] has already been completed
	at com.netease.arctic.io.writer.BaseTaskWriter$OrderedWriterHolder.getDataWriter(BaseTaskWriter.java:292)
	at com.netease.arctic.io.writer.BaseTaskWriter$WriterHolder.get(BaseTaskWriter.java:187)
	at com.netease.arctic.io.writer.BaseTaskWriter.write(BaseTaskWriter.java:81)
	at com.netease.arctic.spark.writer.SimpleKeyedUpsertDataWriter.write(SimpleKeyedUpsertDataWriter.java:38)
	at com.netease.arctic.spark.writer.SimpleKeyedUpsertDataWriter.write(SimpleKeyedUpsertDataWriter.java:19)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$1(WriteToDataSourceV2Exec.scala:416)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1473)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:452)
	at com.netease.arctic.shade.org.apache.spark.sql.execution.datasources.v2.ArcticTableWriteExec.$anonfun$writeInsert$2(ArcticTableWriteExec.scala:81)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:498)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:501)
	... 3 more

	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.operation.ExecuteStatement.waitStatementComplete(ExecuteStatement.scala:119)
	at org.apache.kyuubi.operation.ExecuteStatement.$anonfun$runInternal$1(ExecuteStatement.scala:154)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) (state=,code=0)
```

### Affects Versions

master

### What engines are you seeing the problem on?

Spark

### How to reproduce

According to 'What happened?'.Just execute the SQL, and the source table is the TPCH's `lineitem`.

### Relevant log output

```shell
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2303)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2252)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2251)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2251)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1124)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1124)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1124)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2490)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2432)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2421)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:902)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
	at com.netease.arctic.shade.org.apache.spark.sql.execution.datasources.v2.ArcticTableWriteExec.writeInsert(ArcticTableWriteExec.scala:78)
	... 31 more
Caused by: java.lang.IllegalStateException: The write key [[8075] TreeNode(3,3)] has already been completed
	at com.netease.arctic.io.writer.BaseTaskWriter$OrderedWriterHolder.getDataWriter(BaseTaskWriter.java:292)
	at com.netease.arctic.io.writer.BaseTaskWriter$WriterHolder.get(BaseTaskWriter.java:187)
	at com.netease.arctic.io.writer.BaseTaskWriter.write(BaseTaskWriter.java:81)
	at com.netease.arctic.spark.writer.SimpleKeyedUpsertDataWriter.write(SimpleKeyedUpsertDataWriter.java:38)
	at com.netease.arctic.spark.writer.SimpleKeyedUpsertDataWriter.write(SimpleKeyedUpsertDataWriter.java:19)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$1(WriteToDataSourceV2Exec.scala:416)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1473)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:452)
	at com.netease.arctic.shade.org.apache.spark.sql.execution.datasources.v2.ArcticTableWriteExec.$anonfun$writeInsert$2(ArcticTableWriteExec.scala:81)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:498)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:501)
	... 3 more

	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.operation.ExecuteStatement.waitStatementComplete(ExecuteStatement.scala:119)
	at org.apache.kyuubi.operation.ExecuteStatement.$anonfun$runInternal$1(ExecuteStatement.scala:154)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) (state=,code=0)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
If upsert with different partition on same key,  the optimize write will not work because we can only sort on UPDATE_BEFORE or UPDATE_AFTER
