### ISSUE TITLE
[Improvement]: Start the AMS server failed when derby database path already exists

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/arctic#1303]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I build the 0.4.1 version project locally and run the `dist/target/arctic-0.4.1/bin/ams.sh start`. It returns message show ran succeed:
```
$ bin/ams.sh start
starting app server.
process start success.
```
Actually, the AMS server didn't run successfully. Checked the AMS error logs and found:
```
Caused by: org.apache.derby.iapi.error.StandardException: The database directory '/private/tmp/arctic/derby' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at org.apache.derby.impl.services.monitor.StorageFactoryService.access$900(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at org.apache.derby.impl.services.monitor.StorageFactoryService$10.run(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_221]
        at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source) ~[derby-10.13.1.1.jar:?]
        at org.apache.derby.impl.jdbc.EmbedConnection$5.run(Unknown Source) ~[derby-10.13.1.1.jar:?]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Aireed** [comment]
OK, i will take a look soon
