### ISSUE TITLE
[Bug]: Mixed Format Table's Major optimizing can't commit when there is no target files

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#1420]
### What happened?

After PR #1324 is cherry-picked to 0.3.x, the major optimizing's commit will fail when all records an deleted after optimizing, and the exception message is as follows
```
2023-05-06 11:24:40,061 WARN [main] [com.netease.arctic.ams.server.optimize.BaseOptimizeCommit] [] - Optimize commit table test_catalog.test_db.test_pk_table failed, give up commit and clear files in location.
java.lang.IllegalArgumentException: Data files to add can not be empty because there's no delete file to be rewritten
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[iceberg-bundled-guava-0.12.0.jar:?]
	at org.apache.iceberg.BaseRewriteFiles.verifyInputAndOutputFiles(BaseRewriteFiles.java:62) ~[iceberg-core-0.12.0.jar:?]
	at org.apache.iceberg.BaseRewriteFiles.rewriteFiles(BaseRewriteFiles.java:72) ~[iceberg-core-0.12.0.jar:?]
	at com.netease.arctic.trace.TracedRewriteFiles.rewriteFiles(TracedRewriteFiles.java:52) ~[classes/:?]
	at com.netease.arctic.ams.server.optimize.BaseOptimizeCommit.majorCommit(BaseOptimizeCommit.java:336) ~[classes/:?]
	at com.netease.arctic.ams.server.optimize.BaseOptimizeCommit.commit(BaseOptimizeCommit.java:135) ~[classes/:?]
```

### Affects Versions

0.3.2

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. create an Mixed Iceberg Keyed Table (with 0.3.x)
2. write some records (into change store)
3. wait for Minor Optimizing
4. delete all records
5. wait for Minor Optimizing and Major Optimizing
6. the Major Optimizing will fail when commit

### Anything else

#478 is trying to fix this problem, However, it brings about the issue of data inconsistency as #1319

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
This issue only occurs with Iceberg version < 0.13. So, The master and 0.4.x are not affected.

**Comment by zhoujinsong** [comment]
> Affects Versions

Try to correct `Affects Versions` in the description.

**Comment by wangtaohz** [comment]
> Try to correct `Affects Versions` in the description.

OK, only 0.3.2 is affected.

**Comment by zhoujinsong** [comment]
Affecting user workflow, classified as critical.
