### ISSUE TITLE
[Bug]: When the target column doesn't contain primary key, reading from Arctic Filestore will encounter NullPointerException.

### ISSUE THREAD

**Issue by lklhdu** [NetEase/arctic#1451]
### What happened?

When the target column doesn't contain primary key, reading from Arctic Filestore will encounter NullPointerException.

### Affects Versions

master

### What engines are you seeing the problem on?

Flink

### How to reproduce

```
create table arctic_catalog.test.tb (
    id int,
    user_id int, 
    street string,
    user_name string,
    primary key (id)
) using arctic;

create table print_tb(
    user_id int, 
    street string
) WITH (
'connector' = 'print'
);

insert into print_tb 
select user_id, street from arctic_catalog.test.tb 
where user_id > 1000;
```

### Relevant log output

```shell
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:199)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:154)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:116)
	at com.netease.arctic.flink.read.hybrid.reader.ArcticSourceReader.pollNext(ArcticSourceReader.java:128)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:275)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:67)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:398)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:619)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:583)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:758)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:573)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:146)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.NullPointerException
	at com.netease.arctic.data.PrimaryKeyData.<init>(PrimaryKeyData.java:57)
	at com.netease.arctic.utils.NodeFilter.<init>(NodeFilter.java:45)
	at com.netease.arctic.io.reader.AbstractIcebergDataReader.<init>(AbstractIcebergDataReader.java:91)
	at com.netease.arctic.hive.io.reader.AbstractAdaptHiveIcebergDataReader.<init>(AbstractAdaptHiveIcebergDataReader.java:76)
	at com.netease.arctic.flink.read.source.FlinkArcticDataReader.<init>(FlinkArcticDataReader.java:66)
	at com.netease.arctic.flink.read.hybrid.reader.RowDataReaderFunction.createDataIterator(RowDataReaderFunction.java:87)
	at com.netease.arctic.flink.read.hybrid.reader.DataIteratorReaderFunction.apply(DataIteratorReaderFunction.java:42)
	at com.netease.arctic.flink.read.hybrid.reader.DataIteratorReaderFunction.apply(DataIteratorReaderFunction.java:31)
	at com.netease.arctic.flink.read.hybrid.reader.HybridSplitReader.fetch(HybridSplitReader.java:67)
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:56)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:138)
	... 6 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Affecting user workflow, classified as critical.
