### ISSUE TITLE
[Bug]: Self-Optimizing cached table list not fetched correctly

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#1474]
### What happened?

![image](https://github.com/NetEase/arctic/assets/109209550/755bd6b5-02a8-477d-b11e-fd3d66a9f685)
![image](https://github.com/NetEase/arctic/assets/109209550/207b50d1-2161-4ac6-bf22-e1d6fbd69010)
![image](https://github.com/NetEase/arctic/assets/109209550/cc95ced9-d910-403d-aabb-97baf42902a1)
As you can see my Arctic table actually exists in AMS, but getTableOptimizeItem is still unable to load the table, a behaviour that may prevent Self-Optimizing from progressing smoothly
![image](https://github.com/NetEase/arctic/assets/109209550/605d391b-b308-4feb-8596-c0f3b11ccd2b)
There is a greater risk that this function will be quoted in more than one place

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. Not sure of the exact method of recurrence

### Relevant log output

```shell
2023-05-26 13:59:43,537 ERROR [Metastore Scheduled Table Runtime Data Expire Worker 0] [com.netease.arctic.ams.server.service.impl.RuntimeDataExpireService] [] - arctic_da_luna.da_luna.arctic_xxxxx failed to expire and clear table_task_history table
com.netease.arctic.ams.api.NoSuchObjectException: can't find table arctic_da_luna.da_luna.arctic_xxxxx
        at com.netease.arctic.ams.server.optimize.OptimizeService.getTableOptimizeItem(OptimizeService.java:278) ~[arctic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.service.impl.RuntimeDataExpireService.lambda$expire$0(RuntimeDataExpireService.java:74) ~[arctic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_261]
        at com.netease.arctic.ams.server.service.impl.RuntimeDataExpireService.expire(RuntimeDataExpireService.java:70) ~[arctic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.service.impl.RuntimeDataExpireService.doExpire(RuntimeDataExpireService.java:60) ~[arctic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aireed** [comment]
Overdue logic should first check whether the table has enabled self-optimization。 i will fix it
![image](https://github.com/NetEase/arctic/assets/8862395/8978360c-9377-4c26-b886-20ef7f17d772)
![image](https://github.com/NetEase/arctic/assets/8862395/6eef4ca8-3e47-4573-b4a0-46121b60a2d0)
