### ISSUE TITLE
[Bug]: Self-Optimizing does not perform the commit operation properly

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#1475]
### What happened?

![image](https://github.com/NetEase/arctic/assets/109209550/48913116-a769-49e7-bd43-bf5d379cab1d)
You can see that when Self-Optimizing tries to synchronize the new partition with the hive table, it finds that the partition already exists, so there is no way to commit it properly

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

Core, AMS

### How to reproduce

Not sure of the exact method of recurrence

### Relevant log output

```shell
2023-05-25 10:48:42,367 WARN [Metastore Scheduled Commit Worker 3] [com.netease.arctic.ams.server.optimize.BasicOptim
izeCommit] [] - Optimize commit table arctic_xxxxx.xxxxx.arctic_xxxxx failed, give up commit and cl
ear files in location.
com.netease.arctic.hive.exceptions.CannotAlterHiveLocationException: can't create new partition: Partition(values: [2
023-05-06], location: hdfs://xxxxxx/user/hive/warehouse/xxxxxx.db/arctic_xxxxxxx/hive/day=2023-05-06/1
684982915057_4981), this partition exists in hive with different location: hdfs://xxxxx/user/hive/warehouse/xxxxxx.db/arctic_xxxxxxx/hive/day=2023-05-06/1683648319364_3292
        at com.netease.arctic.hive.op.UpdateHiveFiles.filterNewPartitionNonExists(UpdateHiveFiles.java:348) ~[arctic-
hive-0.4.1-SNAPSHOT.jar:?]
        at com.netease.arctic.hive.op.UpdateHiveFiles.getCreatePartition(UpdateHiveFiles.java:200) ~[arctic-hive-0.4.
1-SNAPSHOT.jar:?]
        at com.netease.arctic.hive.op.UpdateHiveFiles.commit(UpdateHiveFiles.java:105) ~[arctic-hive-0.4.1-SNAPSHOT.j
ar:?]
        at com.netease.arctic.ams.server.optimize.BasicOptimizeCommit.majorCommit(BasicOptimizeCommit.java:361) ~[arc
tic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.BasicOptimizeCommit.commit(BasicOptimizeCommit.java:145) [arctic-am
s-server-0.4.1-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.SupportHiveCommit.commit(SupportHiveCommit.java:129) [arctic-ams-se
rver-0.4.1-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.commitOptimizeTasks(TableOptimizeItem.java:1057)
[arctic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCommitWorker.run(OptimizeCommitWorker.java:49) [arctic-ams-
server-0.4.1-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecuto
r.java:180) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:
293) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aireed** [comment]
after we check  and reproduce,   this is same with https://github.com/NetEase/arctic/issues/1456,  so i closed it!

reproduce:
1、delete all data of some partition, the partition is still in the metadata json ,but  not exist in hive metastore. 

![image](https://github.com/NetEase/arctic/assets/8862395/e23cc8b8-1e8a-4591-954f-e262fd8ac158)
![image](https://github.com/NetEase/arctic/assets/8862395/1448be97-c8f2-40c3-be85-ea8545553e82)
