### ISSUE TITLE
[Bug]: AMS start faied

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#1538]
### What happened?

AMS start hang.
I found `initialized.get()` impossible to succeed, beacuse `initialized.complete()` after this stack.
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.netease.arctic.server.table.DefaultTableService.checkStarted(DefaultTableService.java:421)
	  at com.netease.arctic.server.table.DefaultTableService.contains(DefaultTableService.java:340)
	  at com.netease.arctic.server.table.executor.BaseTableExecutor.isExecutable(BaseTableExecutor.java:82)
	  at com.netease.arctic.server.table.executor.BaseTableExecutor.scheduleIfNecessary(BaseTableExecutor.java:63)
	  at com.netease.arctic.server.table.executor.OptimizingCommitExecutor.handleStatusChanged(OptimizingCommitExecutor.java:37)
	  at com.netease.arctic.server.table.RuntimeHandlerChain.lambda$fireStatusChanged$0(RuntimeHandlerChain.java:37)
	  at com.netease.arctic.server.table.RuntimeHandlerChain$$Lambda$196.1497444850.run(Unknown Source:-1)
	  at com.netease.arctic.server.table.RuntimeHandlerChain.doSilently(RuntimeHandlerChain.java:73)
	  at com.netease.arctic.server.table.RuntimeHandlerChain.fireStatusChanged(RuntimeHandlerChain.java:37)
	  at com.netease.arctic.server.table.RuntimeHandlerChain.fireStatusChanged(RuntimeHandlerChain.java:39)
	  at com.netease.arctic.server.table.RuntimeHandlerChain.fireStatusChanged(RuntimeHandlerChain.java:39)
	  at com.netease.arctic.server.table.RuntimeHandlerChain.fireStatusChanged(RuntimeHandlerChain.java:39)
	  at com.netease.arctic.server.table.DefaultTableService.handleTableChanged(DefaultTableService.java:279)
	  at com.netease.arctic.server.table.TableRuntime.lambda$completeProcess$11(TableRuntime.java:241)
	  at com.netease.arctic.server.table.TableRuntime$$Lambda$194.600661314.run(Unknown Source:-1)
	  at com.netease.arctic.server.persistence.StatedPersistentBase.invokeConsisitency(StatedPersistentBase.java:31)
	  at com.netease.arctic.server.table.TableRuntime.completeProcess(TableRuntime.java:220)
	  at com.netease.arctic.server.optimizing.OptimizingQueue$TableOptimizingProcess.lambda$persistProcessCompleted$13(OptimizingQueue.java:556)
	  at com.netease.arctic.server.optimizing.OptimizingQueue$TableOptimizingProcess$$Lambda$180.196237139.run(Unknown Source:-1)
	  at com.netease.arctic.server.persistence.PersistentBase.doAsTransaction(PersistentBase.java:61)
	  at com.netease.arctic.server.optimizing.OptimizingQueue.access$700(OptimizingQueue.java:51)
	  at com.netease.arctic.server.optimizing.OptimizingQueue$TableOptimizingProcess.persistProcessCompleted(OptimizingQueue.java:551)
	  at com.netease.arctic.server.optimizing.OptimizingQueue$TableOptimizingProcess.close(OptimizingQueue.java:363)
	  at com.netease.arctic.server.optimizing.OptimizingQueue.initTableRuntime(OptimizingQueue.java:111)
	  at com.netease.arctic.server.optimizing.OptimizingQueue$$Lambda$162.2010350054.accept(Unknown Source:-1)
	  at java.util.ArrayList.forEach(ArrayList.java:1259)
	  at com.netease.arctic.server.optimizing.OptimizingQueue.<init>(OptimizingQueue.java:82)
	  at com.netease.arctic.server.DefaultOptimizingService.lambda$loadOptimizingQueues$2(DefaultOptimizingService.java:107)
	  at com.netease.arctic.server.DefaultOptimizingService$$Lambda$155.2138849804.accept(Unknown Source:-1)
	  at java.util.ArrayList.forEach(ArrayList.java:1259)
	  at com.netease.arctic.server.DefaultOptimizingService.loadOptimizingQueues(DefaultOptimizingService.java:101)
	  at com.netease.arctic.server.DefaultOptimizingService$TableRuntimeHandlerImpl.initHandler(DefaultOptimizingService.java:242)
	  at com.netease.arctic.server.table.RuntimeHandlerChain.startHandler(RuntimeHandlerChain.java:30)
	  at com.netease.arctic.server.table.DefaultTableService.initialize(DefaultTableService.java:305)
	  at com.netease.arctic.server.ArcticServiceContainer.startService(ArcticServiceContainer.java:124)
	  at com.netease.arctic.server.ArcticServiceContainer.main(ArcticServiceContainer.java:88)

```

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. disable table optimize
2. restart AMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shidayang** [comment]
I will follow this issue

**Comment by shidayang** [comment]
@zhongqishang I got the reason for this error，During initialization, DefaultTableService#initialize initializes the RuntimeHandlerChain. In the RuntimeHandlerChain system, the DefaultOptimizingService$TableRuntimeHandlerImpl#initHandler method causes the OptimizingQueue's line 111 code to call the OptimizingProcess.close() method. This method changes the state of a series of subsequent RuntimeHandlerChains and performs corresponding operations. These operations call the BaseTableExecutor#isExecutable method to check if the table can be executed. This method calls the DefaultTableService#contain method to check if the table exists, but this method requires the DefaultTableService to be initialized, which is not yet completed, causing the program to hang.

 So we can add a flag in the BaseTableExecutor class to only respond to the corresponding status after initialization is completed. BTW you can rename RuntimeHandlerChain#startHandler to RuntimeHandlerChain#initialize
