### ISSUE TITLE
Flink task writes the Arctic table from the kafka table. When the Flink task fails frequently, the Ams server will report an error.

### ISSUE THREAD

**Issue by 1272870698** [NetEase/arctic#161]
The Flink task writes the Arctic table from the kafka table. When the Flink task fails frequently, the Ams server will report an error. The error message is as follows:

`
Error querying database.  Cause: java.sql.SQLException: Cannot get a connection, pool error Timeout waiting for idle object
The error may exist in com/netease/arctic/ams/server/mapper/CatalogMetadataMapper.java (best guess)
The error may involve com.netease.arctic.ams.server.mapper.CatalogMetadataMapper.getCatalog
The error occurred while executing a query
 Cause: java.sql.SQLException: Cannot get a connection, pool error Timeout waiting for idle object
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.5.jar:3.5.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149) ~[mybatis-3.5.5.jar:3.5.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.5.jar:3.5.5]
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147) ~[mybatis-3.5.5.jar:3.5.5]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80) ~[mybatis-3.5.5.jar:3.5.5]
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152) ~[mybatis-3.5.5.jar:3.5.5]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85) ~[mybatis-3.5.5.jar:3.5.5]
	at com.sun.proxy.$Proxy32.getCatalog(Unknown Source) ~[?:?]
	at com.netease.arctic.ams.server.service.impl.CatalogMetadataService.getCatalog(CatalogMetadataService.java:43) ~[arctic-ams-server-0.3.0.jar:?]
	at com.netease.arctic.ams.server.handler.impl.ArcticTableMetastoreHandler.getCatalog(ArcticTableMetastoreHandler.java:70) ~[arctic-ams-server-0.3.0.jar:?]
	at com.netease.arctic.ams.api.ArcticTableMetastore$Processor$getCatalog.getResult(ArcticTableMetastore.java:924) ~[arctic-ams-api-0.3.0.jar:?]
	at com.netease.arctic.ams.api.ArcticTableMetastore$Processor$getCatalog.getResult(ArcticTableMetastore.java:903) ~[arctic-ams-api-0.3.0.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:138) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:524) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.server.Invocation.run(Invocation.java:18) ~[libthrift-0.13.0.jar:0.13.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_241]

`

**Comment by hameizi** [comment]
Thanks for @1272870698 . This have fixed in https://github.com/NetEase/arctic/pull/160. I will close thie issue.
