### ISSUE TITLE
[Bug]: Without any container configuration, AMS startup will result in an NPE error

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#1636]
### What happened?

I configured AMS with only one external optimizer group, with the config.yaml as follows
```
containers:
optimizer_groups:
  - name: default
    container: external # The external container is used to host all externally launched optimizers.
```

where the `containers` is empty. And I got an exception when starting AMS
```
2023-06-30 15:44:21,351 ERROR [main] [com.netease.arctic.server.ArcticServiceContainer] [] - AMS encountered an unknown exception, will exist
java.lang.NullPointerException: null
	at com.netease.arctic.server.ArcticServiceContainer$ConfigurationHelper.initContainerConfig(ArcticServiceContainer.java:309) ~[classes/:?]
	at com.netease.arctic.server.ArcticServiceContainer$ConfigurationHelper.init(ArcticServiceContainer.java:225) ~[classes/:?]
	at com.netease.arctic.server.ArcticServiceContainer.initConfig(ArcticServiceContainer.java:156) ~[classes/:?]
	at com.netease.arctic.server.ArcticServiceContainer.<init>(ArcticServiceContainer.java:80) ~[classes/:?]
	at com.netease.arctic.server.ArcticServiceContainer.main(ArcticServiceContainer.java:86) ~[classes/:?]
```

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

Set the config.yaml like
```
...
...
...
containers:
optimizer_groups:
  - name: default
    container: external # The external container is used to host all externally launched optimizers.
```

Then restart AMS.

### Relevant log output

```shell
2023-06-30 15:44:21,351 ERROR [main] [com.netease.arctic.server.ArcticServiceContainer] [] - AMS encountered an unknown exception, will exist
java.lang.NullPointerException: null
	at com.netease.arctic.server.ArcticServiceContainer$ConfigurationHelper.initContainerConfig(ArcticServiceContainer.java:309) ~[classes/:?]
	at com.netease.arctic.server.ArcticServiceContainer$ConfigurationHelper.init(ArcticServiceContainer.java:225) ~[classes/:?]
	at com.netease.arctic.server.ArcticServiceContainer.initConfig(ArcticServiceContainer.java:156) ~[classes/:?]
	at com.netease.arctic.server.ArcticServiceContainer.<init>(ArcticServiceContainer.java:80) ~[classes/:?]
	at com.netease.arctic.server.ArcticServiceContainer.main(ArcticServiceContainer.java:86) ~[classes/:?]
```
```


### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
Resolved by this issue #2188
