### ISSUE TITLE
[Improvement]: Reduce the size of the serialization of rewritten files

### ISSUE THREAD

**Issue by XBaith** [NetEase/arctic#1650]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

For tables with many rewritten files, it is more challenging for DB to read and write records in a single transaction.

### How should we improve?

Try to reduce the size of the serialization of rewritten files first

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XBaith** [comment]
```
2023-07-04 06:57:20,651 ERROR [pool-10-thread-18] [com.netease.arctic.server.optimizing.OptimizingQueue] [] - catalog.db.table(tableId=37) plan failed, continue
com.netease.arctic.server.exception.PersistenceException: org.apache.ibatis.exceptions.PersistenceException: 
### Error committing transaction.  Cause: java.sql.SQLException: message:"raft entry is too large, region 40146788, entry size 39380841" raft_entry_too_large:<region_id:40146788 entry_size:39380841 > 
### Cause: java.sql.SQLException: message:"raft entry is too large, region 40146788, entry size 39380841" raft_entry_too_large:<region_id:40146788 entry_size:39380841 > 
        at com.netease.arctic.server.exception.ArcticRuntimeException.wrap(ArcticRuntimeException.java:123) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.persistence.PersistentBase.doAsTransaction(PersistentBase.java:66) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.optimizing.OptimizingQueue.access$600(OptimizingQueue.java:52) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.optimizing.OptimizingQueue$TableOptimizingProcess.beginAndPersistProcess(OptimizingQueue.java:540) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.optimizing.OptimizingQueue$TableOptimizingProcess.<init>(OptimizingQueue.java:334) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.optimizing.OptimizingQueue.planTasks(OptimizingQueue.java:284) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.optimizing.OptimizingQueue.pollOrPlan(OptimizingQueue.java:257) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
--
        at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:806) ~[mysql-connector-java-8.0.30.jar:8.0.30]
        at org.apache.commons.dbcp2.DelegatingConnection.commit(DelegatingConnection.java:191) ~[commons-dbcp2-2.9.0.jar:2.9.0]
        at org.apache.commons.dbcp2.DelegatingConnection.commit(DelegatingConnection.java:191) ~[commons-dbcp2-2.9.0.jar:2.9.0]
        at org.apache.ibatis.transaction.jdbc.JdbcTransaction.commit(JdbcTransaction.java:72) ~[mybatis-3.5.6.jar:3.5.6]
        at org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:244) ~[mybatis-3.5.6.jar:3.5.6]
        at org.apache.ibatis.executor.CachingExecutor.commit(CachingExecutor.java:119) ~[mybatis-3.5.6.jar:3.5.6]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:223) ~[mybatis-3.5.6.jar:3.5.6]
        at com.netease.arctic.server.persistence.NestedSqlSession.commit(NestedSqlSession.java:51) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.persistence.PersistentBase.doAsTransaction(PersistentBase.java:63) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        ... 23 more
```

**Comment by XBaith** [comment]
```
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLException: entry too large, the max entry size is 125829120, the size of data is 185358682
### The error may exist in com/netease/arctic/server/persistence/mapper/OptimizingMapper.java (best guess)
### The error may involve com.netease.arctic.server.persistence.mapper.OptimizingMapper.updateProcessInputFiles-Inline
### The error occurred while setting parameters
### SQL: UPDATE table_optimizing_process SET rewrite_input = ? WHERE process_id = ?
### Cause: java.sql.SQLException: entry too large, the max entry size is 125829120, the size of data is 185358682
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.6.jar:3.5.6]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199) ~[mybatis-3.5.6.jar:3.5.6]
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67) ~[mybatis-3.5.6.jar:3.5.6]
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152) ~[mybatis-3.5.6.jar:3.5.6]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85) ~[mybatis-3.5.6.jar:3.5.6]
        at com.sun.proxy.$Proxy45.updateProcessInputFiles(Unknown Source) ~[?:?]
        at com.netease.arctic.server.persistence.TaskFilesPersistence$DatabasePersistence.lambda$persistTaskInputs$0(TaskFilesPersistence.java:42) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.persistence.PersistentBase.doAs(PersistentBase.java:48) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        ... 27 more
Caused by: java.sql.SQLException: entry too large, the max entry size is 125829120, the size of data is 185358682
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.30.jar:8.0.30]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.30.jar:8.0.30]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-java-8.0.30.jar:8.0.30]
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354) ~[mysql-connector-java-8.0.30.jar:8.0.30]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94) ~[commons-dbcp2-2.9.0.jar:2.9.0]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94) ~[commons-dbcp2-2.9.0.jar:2.9.0]
        at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.5.6.jar:3.5.6]
```

**Comment by zhongqishang** [comment]
@XBaith @baiyangtx I found that the java native serialization method is used now, can we change to a third-party serialization framework (such as kyro) to get smaller serialization results.
