### ISSUE TITLE
[Bug]: Terminal can not work after upgrade spark to 3.3

### ISSUE THREAD

**Issue by shidayang** [NetEase/arctic#1695]
### What happened?

When I using terminal, I encounter follow exception
```
2023/07/13 10:36:42 java.lang.RuntimeException: run with ugi request failed.
	at com.netease.arctic.table.TableMetaStore.doAsUgi(TableMetaStore.java:370)
	at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873)
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:345)
	at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.get(TerminalSessionContext.java:193)
	at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.get(TerminalSessionContext.java:164)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchFieldError: transportConf
	at org.apache.spark.network.netty.NettyBlockTransferService.init(NettyBlockTransferService.scala:72)
	at org.apache.spark.storage.BlockManager.initialize(BlockManager.scala:507)
	at org.apache.spark.SparkContext.(SparkContext.scala:610)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2714)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:942)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:936)
	at com.netease.arctic.server.terminal.local.LocalSessionFactory.lazyInitContext(LocalSessionFactory.java:122)
	at com.netease.arctic.server.terminal.local.LocalSessionFactory.create(LocalSessionFactory.java:58)
	at com.netease.arctic.server.terminal.TerminalSessionContext.lazyLoadSession(TerminalSessionContext.java:158)
	at com.netease.arctic.server.terminal.TerminalSessionContext.access$200(TerminalSessionContext.java:40)
	at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.lambda$get$0(TerminalSessionContext.java:194)
	at com.netease.arctic.table.TableMetaStore.doAsUgi(TableMetaStore.java:365)
	... 11 more
```

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

AMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
I think this bug related to this issue. https://github.com/NetEase/arctic/issues/1704. 

The spark 3.3 dependend on hadoop-client-api.jar and it contained a conflicted UserGroupInformation class with hadoop-common-2.9.jar.

**Comment by baiyangtx** [comment]
I think we should roll back to spark 3.1 to fix this problem in a quick way. and upgrade to spark 3.3 when we support hadoop 3.x
