### ISSUE TITLE
[Bug]: Major optimize on Iceberg format in upsert mode will encountered an error

### ISSUE THREAD

**Issue by HuangFru** [NetEase/arctic#1696]
### What happened?

When using Iceberg upsert mode based on the primary key in the Flink, using the duplicated primary key will encounter an error.
It seems that the sequence of the schema has some problems.

### Affects Versions

master

### What engines are you seeing the problem on?

Optimizer

### How to reproduce

CREATE TABLE IF NOT EXISTS `hadoop_catalog`.`test_db`.`test_table9` ( 
`dt` STRING,
`pt` timestamp_ltz(3),
`ts` timestamp_ltz(3),
`id` bigint not null,
`coupon_id` bigint,
 PRIMARY KEY (`id`,`dt`) NOT ENFORCED
) 
PARTITIONED BY (`dt`)
WITH ( 
'format-version' = '2',
'write.upsert.enabled' = 'true',
'engine.hive.enabled' = 'true',
'catalog-database' = 'dl_ods',
'write.metadata.previous-versions-max' = '1',
'write.metadata.delete-after-commit.enabled' = 'true',
'write.delete.mode' = 'merge-on-read',
'write.delete.isolation-level'='snapshot',
'write.update.mode' = 'merge-on-read',
'write.update.isolation-level'='snapshot',
'write.merge.mode' = 'merge-on-read',
'write.merge.isolation-level'='snapshot',
'write.distribution-mode' = 'hash',
'write.merge.distribution-mode'='hash',
'commit.manifest.min-count-to-merge'='10',
'commit.manifest-merge.enabled'='true',
'history.expire.max-snapshot-age-ms'='3600000',
'history.expire.max-ref-age-ms'='3600000',
'history.expire.min-snapshots-to-keep'='1'
);
Let this table do the major optimize and should be produced pos-deletes.

### Relevant log output

```shell
java.lang.IllegalStateException: Not an instance of java.lang.CharSequence: 1081864790937031308
        at org.apache.iceberg.data.GenericRecord.get(GenericRecord.java:123) ~[iceberg-core-1.1.0.jar:?]
        at com.netease.arctic.iceberg.StructProjection.get(StructProjection.java:157) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at org.apache.iceberg.types.Comparators$StructLikeComparator.compare(Comparators.java:111) ~[iceberg-api-1.1.0.jar:?]
        at org.apache.iceberg.types.Comparators$StructLikeComparator.compare(Comparators.java:84) ~[iceberg-api-1.1.0.jar:?]
        at com.netease.arctic.iceberg.StructLikeWrapper.equals(StructLikeWrapper.java:85) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at java.util.HashMap.getNode(HashMap.java:572) ~[?:1.8.0_152]
        at java.util.HashMap.get(HashMap.java:557) ~[?:1.8.0_152]
        at com.netease.arctic.utils.map.StructLikeMemoryMap$SimpleMemoryMap.get(StructLikeMemoryMap.java:65) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.utils.map.StructLikeMemoryMap$SimpleMemoryMap.get(StructLikeMemoryMap.java:49) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.utils.map.StructLikeBaseMap.get(StructLikeBaseMap.java:41) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.iceberg.CombinedDeleteFilter.lambda$applyEqDeletes$3(CombinedDeleteFilter.java:215) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at java.util.function.Predicate.lambda$or$2(Predicate.java:101) ~[?:1.8.0_152]
        at com.netease.arctic.iceberg.CombinedDeleteFilter$1.shouldKeep(CombinedDeleteFilter.java:167) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.iceberg.CombinedDeleteFilter$1.shouldKeep(CombinedDeleteFilter.java:164) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at org.apache.iceberg.util.Filter$Iterator.shouldKeep(Filter.java:48) ~[iceberg-core-1.1.0.jar:?]
        at org.apache.iceberg.io.FilterIterator.advance(FilterIterator.java:66) ~[iceberg-api-1.1.0.jar:?]
        at org.apache.iceberg.io.FilterIterator.hasNext(FilterIterator.java:49) ~[iceberg-api-1.1.0.jar:?]
        at org.apache.iceberg.io.CloseableIterable$7$1.hasNext(CloseableIterable.java:197) ~[iceberg-api-1.1.0.jar:?]
        at com.netease.arctic.optimizing.AbstractRewriteFilesExecutor.equalityToPosition(AbstractRewriteFilesExecutor.java:121) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAsUgi(TableMetaStore.java:365) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:345) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_152]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873) ~[hadoop-common-2.9.2.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:345) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.io.ArcticHadoopFileIO.doAs(ArcticHadoopFileIO.java:191) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.optimizing.AbstractRewriteFilesExecutor.execute(AbstractRewriteFilesExecutor.java:96) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.optimizing.AbstractRewriteFilesExecutor.execute(AbstractRewriteFilesExecutor.java:57) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.optimizer.OptimizerExecutor.executeTask(OptimizerExecutor.java:97) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.optimizer.OptimizerExecutor.start(OptimizerExecutor.java:34) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_152]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
I am working hard to reproduce a similar issue, and this issue has greatly helped me!

**Comment by HuangFru** [comment]
This is because the delete filter and the primary key project did not use the same schema so causing the primary key projection to be out of order in StuckLike.
Actually, the delete filter uses the table's schema, and the pk projection uses the required scheme, they may be different.
