### ISSUE TITLE
[Bug]: flink source project pushdown would cause reading all fields to downstream

### ISSUE THREAD

**Issue by zstraw** [NetEase/arctic#257]
### What happened?

Select partial fields from arctic table, but there will be all fields without projecting. It will cause unmatched rowtype and real rowdata. And shuffle is using all fields RowType, which may cause ArrayIndexOutOfBoundsException.

### Affects Versions

master/0.3.1

### What engines are you seeing the problem on?

Flink

### How to reproduce

Create a table t with fields a string, b int, c string.  And declare c as partition key. Then select a, c from t. 

### Relevant log output

```shell
java.lang.RuntimeException: 4
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.pushToRecordWriter(RecordWriterOutput.java:109)
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.collect(RecordWriterOutput.java:93)
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.collect(RecordWriterOutput.java:44)
	at org.apache.flink.streaming.runtime.tasks.SourceOperatorStreamTask$AsyncDataOutputToOutput.emitRecord(SourceOperatorStreamTask.java:188)
	at org.apache.flink.streaming.api.operators.source.SourceOutputWithWatermarks.collect(SourceOutputWithWatermarks.java:110)
	at org.apache.flink.streaming.api.operators.source.SourceOutputWithWatermarks.collect(SourceOutputWithWatermarks.java:101)
	at com.netease.arctic.flink.read.hybrid.reader.ArcticRecordEmitter.emitRecord(ArcticRecordEmitter.java:35)
	at com.netease.arctic.flink.read.hybrid.reader.ArcticRecordEmitter.emitRecord(ArcticRecordEmitter.java:28)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:128)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:275)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:67)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:398)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:619)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:583)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:758)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:573)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
	at org.apache.flink.table.data.GenericRowData.isNullAt(GenericRowData.java:129)
	at org.apache.iceberg.flink.RowDataWrapper.get(RowDataWrapper.java:68)
	at org.apache.iceberg.Accessors$PositionAccessor.get(Accessors.java:71)
	at org.apache.iceberg.Accessors$PositionAccessor.get(Accessors.java:58)
	at org.apache.iceberg.PartitionKey.partition(PartitionKey.java:104)
	at com.netease.arctic.flink.shuffle.ShuffleHelper.hashPartitionValue(ShuffleHelper.java:110)
	at com.netease.arctic.flink.shuffle.ReadShuffleRulePolicy$RoundRobinPartitioner.partition(ReadShuffleRulePolicy.java:111)
	at com.netease.arctic.flink.shuffle.ReadShuffleRulePolicy$RoundRobinPartitioner.partition(ReadShuffleRulePolicy.java:83)
	at org.apache.flink.streaming.runtime.partitioner.CustomPartitionerWrapper.selectChannel(CustomPartitionerWrapper.java:54)
	at org.apache.flink.streaming.runtime.partitioner.CustomPartitionerWrapper.selectChannel(CustomPartitionerWrapper.java:33)
	at org.apache.flink.runtime.io.network.api.writer.ChannelSelectorRecordWriter.emit(ChannelSelectorRecordWriter.java:54)
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.pushToRecordWriter(RecordWriterOutput.java:107)
	... 18 more
```

### Anything else

In #108 supports projection push down. 
But the flinkSchemaRowType in ArcticDynamicSource won't be adjust after projection, which help to build ShuffleHelper.
On the other hand, there is still using all fields schema in buiding RowDataReaderFunction in FlinkSource.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SteNicholas** [comment]
@zstraw, could you please assign this ticket to me? I would like to fix the above bug.

**Comment by zstraw** [comment]
Thanks for your help.
