### ISSUE TITLE
[Bug]: Spark-sql query request failed

### ISSUE THREAD

**Issue by YuChangHui** [NetEase/arctic#691]
### What happened?

I created the database(named test_db) and table(named test_table) in the terminal of AMS according to Arctic's quickstart, and then used the flink cdc to listen to port 9999 and write the data to the table. Later, I tried to use spark sql to read the data in the table. I tried the following methods but failed:
1. use local_catalog;  select * from test_db.test_table;
2. select * from test_db.test_table;
3. select * from local_catalog.test_db.test_table;
I want to know how I can use spark sql to read the data.
I would appreciate it if you could help me.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS, Flink, Spark

### How to reproduce

1. Do the tasks in Arctic quickstart
2. Use spark-sql to read data in the test_table;

### Relevant log output

```shell
spark-sql> use local_catalog;
22/11/22 10:39:54 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
22/11/22 10:39:54 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
Time taken: 0.077 seconds
spark-sql> show databases;
test_db
Time taken: 0.048 seconds, Fetched 1 row(s)
spark-sql> select * from test_db.test_table;
22/11/22 10:40:16 ERROR TableMetaStore: run with catalog ugi request failed. UGI is root (auth:SIMPLE)
com.netease.arctic.shade.org.apache.iceberg.exceptions.NoSuchTableException: Table does not exist at location: /tmp/arctic/warehouse/test_db/test_table/base
	at com.netease.arctic.shade.org.apache.iceberg.hadoop.HadoopTables.load(HadoopTables.java:89)
	at com.netease.arctic.catalog.BaseArcticCatalog.lambda$loadKeyedTable$1(BaseArcticCatalog.java:190)
	at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1666)
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314)
	at com.netease.arctic.catalog.BaseArcticCatalog.loadKeyedTable(BaseArcticCatalog.java:190)
	at com.netease.arctic.catalog.BaseArcticCatalog.loadTableByMeta(BaseArcticCatalog.java:177)
	at com.netease.arctic.catalog.BaseArcticCatalog.loadTable(BaseArcticCatalog.java:170)
	at com.netease.arctic.spark.ArcticSparkCatalog.loadTable(ArcticSparkCatalog.java:136)
	at org.apache.spark.sql.connector.catalog.CatalogV2Util$.loadTable(CatalogV2Util.scala:282)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveTables$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveTables$$lookupV2Relation(Analyzer.scala:1060)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveTables$$anonfun$apply$9.applyOrElse(Analyzer.scala:1005)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveTables$$anonfun$apply$9.applyOrElse(Analyzer.scala:1003)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$3(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:74)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$1(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:221)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:86)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:84)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$2(AnalysisHelper.scala:87)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:408)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:244)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:406)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:359)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$1(AnalysisHelper.scala:87)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:221)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:86)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:84)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveTables$.apply(Analyzer.scala:1003)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveTables$.apply(Analyzer.scala:1002)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:216)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:213)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:205)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:205)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:196)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:190)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:155)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:183)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:183)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:174)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:228)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:173)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:73)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:143)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:143)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:73)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:71)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:63)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:98)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:650)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:67)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:381)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1(SparkSQLCLIDriver.scala:500)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1$adapted(SparkSQLCLIDriver.scala:494)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processLine(SparkSQLCLIDriver.scala:494)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:284)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:949)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:178)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:201)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:88)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1037)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1046)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Error in query: Table or view not found: test_db.test_table; line 1 pos 14;
'Project [*]
+- 'UnresolvedRelation [test_db, test_table], [], false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@YuChangHui  The error log means that spark cannot load the iceberg table from location `/tmp/arctic/warehouse/test_db/test_table/base`, you can follow the steps below to try to find the cause:

The main reason seems to be spark tries to load tables from a remote file system (HDFS) instead of the local file system.

- make sure `/tmp/arctic/warehouse/test_db/test_table/base` folder exists in your local file system and you will find `data` and `metadata` folders inside it.
- find out whether `core-site.xml` and `hdfs-site.xml` existed in your `{spark-home}/conf` folder, if yes try to move them outside of the conf folder or just rename them to the bak file and try spark tour again
- find out whether you had config `HADOOP_HOME` system variables, if yes try to drop it and try spark tour again

The main reason seems to be spark try to load table from a remote file system (HDFS) instead of local file system.

**Comment by zhoujinsong** [comment]
@YuChangHui  Try to check `HADOOP_HOME`   `HADOOP_CONF_DIR`   `HIVE_HOME`  `HIVE_CONF_DIR` system variables too.

**Comment by baiyangtx** [comment]
how do you run quick starts?  run in docker via docker-compose or compile code by maven ?

**Comment by YuChangHui** [comment]
@baiyangtx I run flink and ams in docker via docker-compose

**Comment by YuChangHui** [comment]
@zhoujinsong There are no `HADOOP_HOME` `HADOOP_CONF_DIR` `HIVE_HOME` `HIVE_CONF_DIR` system variables in my computer.

**Comment by baiyangtx** [comment]
`/tmp/arctic/warehouse/test_db/test_table/base`  exists in docker .   but you are running spark out of docker, spark will find `/tmp/arctic/warehouse/test_db/test_table/base` in your compute filesystem, so spark can't find the path.

**Comment by zhoujinsong** [comment]
I agree with @baiyangtx . You may create a soft link `/tmp/arctic/warehouse/` to your ` {docker_path}/data` path. That may be work with minimum operations. Or you can install Arctic/Saprk/Flink manually on your computer.

**Comment by YuChangHui** [comment]
@zhoujinsong @baiyangtx Thanks very much! I will try it right away.

**Comment by zhoujinsong** [comment]
@YuChangHui  You may want to close this issue if you fixed this problem.

**Comment by YuChangHui** [comment]
@zhoujinsong Yes, thank you for reminding me.
