### ISSUE TITLE
[Bug]: Not correctly equals `authMethod`

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#737]
### What happened?

Create a catalog with kerberos authentication and execute sql in terminal.

```
java.lang.IllegalArgumentException: Error auth method:kerberos
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:217) ~[iceberg-bundled-guava-0.13.2.jar:?]
	at com.netease.arctic.table.TableMetaStore.<init>(TableMetaStore.java:121) ~[classes/:?]
	at com.netease.arctic.table.TableMetaStore.<init>(TableMetaStore.java:65) ~[classes/:?]
	at com.netease.arctic.table.TableMetaStore$Builder.build(TableMetaStore.java:635) ~[classes/:?]
	at com.netease.arctic.ams.server.terminal.TerminalManager.getCatalogTableMetaStore(TerminalManager.java:244) ~[classes/:?]
	at com.netease.arctic.ams.server.terminal.TerminalManager.executeScript(TerminalManager.java:92) ~[classes/:?]
	at com.netease.arctic.ams.server.controller.TerminalController.executeScript(TerminalController.java:70) ~[classes/:?]
```

### Affects Versions

0.4.0-SNAPSHOT

### What engines are you seeing the problem on?

AMS

### How to reproduce

Create a catalog with kerberos authentication and execute sql in terminal

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhongqishang** [comment]
@zhoujinsong 
The data is `simple/kerberos` when written to catalog_metadata, TableMetaStore determines this by `equals`, the easiest way is to fix it to `equalsIgnoreCase`, if from the write catalog side it may need to be fixed by the frontend.

**Comment by zhoujinsong** [comment]
@zhongqishang In my opinion, `TableMetaStore` is constructed by `TableMetaStore.Builder`, we can capitalize the `authMethod` parameter in `TableMetaStore.Builder#build` method.

**Comment by zhongqishang** [comment]
> @zhongqishang In my opinion, `TableMetaStore` is constructed by `TableMetaStore.Builder`, we can capitalize the `authMethod` parameter in `TableMetaStore.Builder#build` method.

This is the easiest way to solve the problem, but each time we use the `authMethod` field subsequently, we may miss capitalizing the parameter.
