### ISSUE TITLE
[Bug][Optimizer]: Cannot optimize Iceberg table in external Flink Optimizer 

### ISSUE THREAD

**Issue by XBaith** [NetEase/arctic#784]
### What happened?

Register a external flink optimizer(k8s) to AMS and nothing change to `OptimizeJob.jar`(upgrade flink to 1.14), and failed to do optimize.
Flink logs:
```
2022-11-29 11:37:54,176 ERROR com.netease.arctic.optimizer.operator.BaseTaskExecutor       [] - failed to set partition info OptimizeTaskId(type:Minor, traceId:8c82cbd7-4deb-4713-8fed-6832e85062ba)
java.lang.IllegalStateException: failed when load catalog dls_iceberg
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:151) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.catalog.CatalogLoader.loadCatalog(CatalogLoader.java:177) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:69) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:79) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.buildTable(BaseTaskExecutor.java:190) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.buildArcticTable(BaseTaskExecutor.java:180) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2344) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at java.util.concurrent.ConcurrentHashMap.compute(Unknown Source) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.getArcticTable(BaseTaskExecutor.java:169) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.execute(BaseTaskExecutor.java:120) [blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:74) [blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:40) [blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:418) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:513) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$SwitchingOnClose.collect(StreamSourceContexts.java:103) [flink-dist-1.15.2.jar:1.15.2]
	at com.netease.arctic.optimizer.flink.FlinkConsumer.run(FlinkConsumer.java:54) [blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) [flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:332) [flink-dist-1.15.2.jar:1.15.2]
Caused by: java.lang.RuntimeException: run with catalog ugi doAs request failed.
	at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:321) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at javax.security.auth.Subject.doAs(Unknown Source) ~[?:?]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1824) ~[hadoop-common-2.8.5.jar:?]
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:313) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.catalog.BaseIcebergCatalog.initialize(BaseIcebergCatalog.java:67) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:146) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	... 29 more
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 70
Exception Details:
  Location:
    org/apache/iceberg/hive/HiveCatalog.loadNamespaceMetadata(Lorg/apache/iceberg/catalog/Namespace;)Ljava/util/Map; @70: astore_2
  Reason:
    Type 'org/apache/hadoop/hive/metastore/api/NoSuchObjectException' (current frame, stack[0]) is not assignable to 'org/apache/thrift/TException' (stack map, stack[0])
  Current Frame:
    bci: @26
    flags: { }
    locals: { 'org/apache/iceberg/hive/HiveCatalog', 'org/apache/iceberg/catalog/Namespace' }
    stack: { 'org/apache/hadoop/hive/metastore/api/NoSuchObjectException' }
  Stackmap Frame:
    bci: @70
    flags: { }
    locals: { 'org/apache/iceberg/hive/HiveCatalog', 'org/apache/iceberg/catalog/Namespace' }
    stack: { 'org/apache/thrift/TException' }
  Bytecode:
    0000000: 2a2b b700 219a 0015 bb00 3459 1235 04bd
    0000010: 0036 5903 2b53 b700 37bf 2ab4 0020 2bba
    0000020: 0095 0000 b900 2602 00c0 0096 4d2a 2cb7
    0000030: 0097 4eb2 0005 1298 2b2d b900 8d01 00b9
    0000040: 0032 0400 2db0 4dbb 0034 592c 1235 04bd
    0000050: 0036 5903 2b53 b700 92bf 4dbb 0039 59bb
    0000060: 003a 59b7 003b 1293 b600 3d2b b600 3e12
    0000070: 77b6 003d b600 3f2c b700 40bf 4db8 0042
    0000080: b600 43bb 0039 59bb 003a 59b7 003b 1294
    0000090: b600 3d2b b600 3e12 77b6 003d b600 3f2c
    00000a0: b700 40bf                              
  Exception Handler Table:
    bci [26, 69] => handler: 70
    bci [26, 69] => handler: 70
    bci [26, 69] => handler: 90
    bci [26, 69] => handler: 124
  Stackmap Table:
    same_frame(@26)
    same_locals_1_stack_item_frame(@70,Object[#56])
    same_locals_1_stack_item_frame(@90,Object[#56])
    same_locals_1_stack_item_frame(@124,Object[#65])

	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.apache.iceberg.common.DynConstructors$Builder.impl(DynConstructors.java:155) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:180) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:234) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.catalog.BaseIcebergCatalog.lambda$initialize$0(BaseIcebergCatalog.java:67) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:315) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at javax.security.auth.Subject.doAs(Unknown Source) ~[?:?]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1824) ~[hadoop-common-2.8.5.jar:?]
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:313) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.catalog.BaseIcebergCatalog.initialize(BaseIcebergCatalog.java:67) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:146) ~[blob_p-4130deb77b653fe5ea314933cc883da95148b93c-c54f397ce190f1ad9c610490b48c7b3e:?]
```

AMS info logs keep printing:
```
2022-11-29 11:50:24,756 INFO [Optimize Plan Thread Queue-30001] [com.netease.arctic.ams.server.service.impl.OptimizeQueueService] [] - submitTask into queue k8sFlink-30001 success, OptimizeTaskItem{optimizeTask=BaseOptimizeTask{taskCommitGroup='d205c986-da56-4b32-98b4-8f828c140f67', taskPlanGroup='b0b33099-f664-40d2-a35a-7acc75144dd8', partition='arrivedate=2022-07-03/xxx_bucket=1', baseFileSize=12598342, insertFileSize=0, deleteFileSize=0, eqDeleteFileSize=0, posDeleteFileSize=0, baseFileCnt=22, insertFileCnt=0, deleteFileCnt=0, eqDeleteFileCnt=0, posDeleteFileCnt=0, queueId=30001, createTime=1669721426859, maxChangeTransactionId=-1} OptimizeTask(taskId:OptimizeTaskId(type:Minor, traceId:20bd08bb-8622-4f78-a4ca-8f1084dff16e), tableIdentifier:TableIdentifier(catalog:dls_iceberg, database:xx, tableName:yyy), insertFiles:0, deleteFiles:0, baseFiles:0, posDeleteFiles:0, properties:{max-execute-time=1800000, all-file-cnt=22}), optimizeRuntime=BaseOptimizeRuntime{optimizeTaskId=OptimizeTaskId(type:Minor, traceId:20bd08bb-8622-4f78-a4ca-8f1084dff16e), status=Pending, pendingTime=1669722624743, executeTime=1669722560796, preparedTime=0, reportTime=1669722560889, commitTime=0, costTime=0, jobId=JobId(id:90017, type:Optimize), retry=3, errorMessage=ErrorMessage(failTime:1669722560840, failReason:failed when load catalog dls_iceberg. caused by run with catalog ugi doAs request failed.. caused by Stack map does not match the one at exception handler 70
```

### Affects Versions

master/0.4.x

### What engines are you seeing the problem on?

Core, AMS, Optimizer

### How to reproduce

1. config a hive metastore with iceberg format
2. register exteranl k8s flink optimizer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XBaith** [comment]
Flink Optimizer main args:
```
-a thrift://10.252.125.84:30609  -qn k8sFlink -p 1 -m 2048 --heart-beat 30000
```

**Comment by XBaith** [comment]
Flink Optimizer main args:
```
-a http://xxx:nnnn -qn k8sFlink -p 1 -m 2048 --heart-beat 30000
```

**Comment by wangtaohz** [comment]
What's your iceberg version?

**Comment by XBaith** [comment]
> What's your Iceberg version? There may be some jar conflict in your Flink dependency, and Arctic now works with Iceberg 0.13.2

Iceberg version as same as arctic project, I just build the source code and run the Flink optimizer on k8s

**Comment by zhoujinsong** [comment]
It seems that the construction of the iceberg hive catalog failed in Optimizer.
Are you using the iceberg hive catalog? And what is the version of your Hive Metastore?

**Comment by zhoujinsong** [comment]
BTW, Does the AMS Dashboard can show the databases and tables for this catalog correctly?

**Comment by XBaith** [comment]
> 

yes, Dashboard can display all tables in this catalog

**Comment by XBaith** [comment]
> It seems that the construction of the iceberg hive catalog failed in Optimizer. Are you using the iceberg hive catalog? And what is the version of your Hive Metastore?

Catalog:
![image](https://user-images.githubusercontent.com/54210725/204793612-765b30d3-51ab-4b8d-8eda-6e7774e5be3b.png)
Hive version: 3.1.x

**Comment by XBaith** [comment]
> According to this error message
> 
> ```
> Reason:
>     Type 'org/apache/hadoop/hive/metastore/api/NoSuchObjectException' (current frame, stack[0]) is not assignable to 'org/apache/thrift/TException' (stack map, stack[0])
> ```
> 
> The valid `org/apache/hadoop/hive/metastore/api/NoSuchObjectException` is from the dependency
> 
> ```
>         <dependency>
>             <groupId>org.apache.hive</groupId>
>             <artifactId>hive-metastore</artifactId>
>             <version>2.1.1</version>
>         </dependency>
> ```
> 
> And `OptimizeJob.jar` contains the this depencency `org.apache.hive:hive-metastore:jar:2.1.1:compile`.
> 
> Maybe there is a conflict of this dependency, and the wrong class is used. We'd better check if there are any other jar of `org.apache.hive:hive-metastore` in flink's libs.

Exactly, it is jar conflict in flink docker image which both contains `iceberg-flink-runtime-*` and `flink-sql-connector-hive-*`.
It optimize successfully after i drop them.
Thanks a lot @wangtaohz and @zhoujinsong !

**Comment by XBaith** [comment]
related issue: https://github.com/apache/iceberg/issues/2057
