### ISSUE TITLE
[Bug]: Flink sets watermark on Arctic table fields, but ArrayIndexOutOfBoundsException occurs when reading data

### ISSUE THREAD

**Issue by lklhdu** [NetEase/arctic#957]
### What happened?

For an Arctic table, setting watermark on the time field of the table via Flink and doing a select operation on the table will result in an ArrayIndexOutOfBoundsException error.

### Affects Versions

master

### What engines are you seeing the problem on?

Flink

### How to reproduce

First create an Arctic table, where the field `ts` is a timestamp type field, and set the watermark based on the `ts` field; then do a GROUP BY operation based on this Arctic table and select the target field list, which will trigger the ArrayIndexOutOfBoundsException

### Relevant log output

```shell
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
	at com.netease.arctic.shaded.org.apache.iceberg.relocated.com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:75)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.Spliterators$IntArraySpliterator.forEachRemaining(Spliterators.java:1032)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.netease.arctic.flink.table.ArcticDynamicSource.applyProjection(ArcticDynamicSource.java:252)
	at org.apache.flink.table.planner.plan.rules.logical.PushProjectIntoTableSourceScanRule.onMatch(PushProjectIntoTableSourceScanRule.java:147)
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:229)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@lklhdu Have you addressed the cause of this bug?

**Comment by lklhdu** [comment]
> @lklhdu Have you addressed the cause of this bug?

I have located the cause of the error and will solve the problem as soon as possible

**Comment by zhoujinsong** [comment]
> > @lklhdu Have you addressed the cause of this bug?
> 
> I have located the cause of the error and will solve the problem as soon as possible

Great! I will link this issue to milestone `Release 0.4.1`

**Comment by YesOrNo828** [comment]
@lklhdu  Could you show more example codes to reproduce this exception?

**Comment by lklhdu** [comment]
This problem is caused by the user setting watermark for the arctic table in the following way：
`CREATE TABLE user_tb (
    WATERMARK FOR ts AS ts - INTERVAL '5' SECOND
) LIKE arctic_catalog.test.watermark_tb;`
The schema for the arctic table here is as follows:
```
arctic_catalog.test.watermark_tb(
    id int,
    user_id int,
    name string,
    amount double,
    ts timestamp(3),
    primary key (id) NOT ENFORCED
)
```
The above operations are executed with Flink 1.12
