### ISSUE TITLE
[Bug]: Kerberos authentication failure

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/arctic#965]
### What happened?

ENV : k8s

Occurred during the follow three place, Kerberos authentication failure .

OptimizeQueueService.java:677
IcebergOptimizeCommit.java:165
TableOptimizeItem.java:426

```
2022-12-27 16:19:16,848 ERROR [Metastore Scheduled Commit Worker 0] [com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit] [] - unexpected commit error hive_prod.ods_iceberg.xxx
org.apache.iceberg.exceptions.RuntimeIOException: Failed to open input stream for file: hdfs://xx/data/hive/warehouse/ods_iceberg.db/xxx/metadata/snap-9100413133805774208-1-ef6f8c7b-803e-42ef-9627-c0b767b6c93b.avro
        at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:179) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:320) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:237) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.ManifestLists.read(ManifestLists.java:46) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:141) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.deleteManifests(BaseSnapshot.java:171) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validationHistory(MergingSnapshotProducer.java:489) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:357) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:316) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseRewriteFiles.validate(BaseRewriteFiles.java:108) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:162) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:283) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:282) ~[iceberg-core-0.13.2.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.minorCommit(IcebergOptimizeCommit.java:165) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.commit(IcebergOptimizeCommit.java:96) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.commitOptimizeTasks(TableOptimizeItem.java:915) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCommitWorker.run(OptimizeCommitWorker.java:49) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_141]
Caused by: java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "hd-142.hadoop.com/xxx.xx.xx.xxx"; destination host is: "hd-017.hadoop.com":8020; 
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:805) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1453) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy59.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:259) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy60.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:847) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:836) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:825) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:330) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:289) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:274) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1064) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:332) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:914) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175) ~[iceberg-core-0.13.2.jar:?]
        ... 30 more
Caused by: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
        at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:760) ~[hadoop-common-2.9.2.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_141]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_141]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:723) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:817) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1568) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1399) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy59.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:259) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy60.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:847) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:836) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:825) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:330) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:289) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:274) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1064) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:332) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:914) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175) ~[iceberg-core-0.13.2.jar:?]
        ... 30 more
Caused by: javax.security.sasl.SaslException: GSS initiate failed
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211) ~[?:1.8.0_141]
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:407) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:618) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$2200(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:804) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:800) ~[hadoop-common-2.9.2.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_141]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_141]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:799) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1568) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1399) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy59.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:259) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy60.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:847) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:836) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:825) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:330) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:289) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:274) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1064) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:332) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:914) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175) ~[iceberg-core-0.13.2.jar:?]
        ... 30 more
Caused by: org.ietf.jgss.GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147) ~[?:1.8.0_141]
        at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122) ~[?:1.8.0_141]
        at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187) ~[?:1.8.0_141]
        at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224) ~[?:1.8.0_141]
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212) ~[?:1.8.0_141]
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179) ~[?:1.8.0_141]
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192) ~[?:1.8.0_141]
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:407) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:618) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$2200(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:804) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:800) ~[hadoop-common-2.9.2.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_141]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_141]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:799) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1568) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1399) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy59.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:259) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy60.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:847) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:836) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:825) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:330) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:289) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:274) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1064) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:332) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:914) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175) ~[iceberg-core-0.13.2.jar:?]
        ... 30 more
```

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
@wangtaohz CC.  Seems the error happens when AMS is doing an optimize commit.

**Comment by baiyangtx** [comment]
@zhongqishang Is this happend when you run optimizors by a flink cluster running in k8s?

**Comment by wangtaohz** [comment]
> Is this happend when you run optimizors by a flink cluster running in k8s?

The error message is from AMS, so is the AMS running is k8s?

**Comment by wangtaohz** [comment]
> Failed to find any Kerberos tgt

Maybe we should make sure you have a valid ticket. 

Did this problem appear every time or occasionally? And did it appear for all tables or for this table only?

**Comment by zhongqishang** [comment]
@baiyangtx @wangtaohz AMS is running on k8s.

> Maybe we should make sure you have a valid ticket.

I confirm i have a tiket because merge job is running correctly.

> Did this problem appear every time or occasionally? And did it appear for all tables or for this table only?

In the same code location appear every time.

**Comment by baiyangtx** [comment]
Mixed-format table or iceberg format table ?

**Comment by zhongqishang** [comment]
> Mixed-format table or iceberg format table ?

iceberg format table.

**Comment by wangtaohz** [comment]
> Not using doAs() properly to operate HDFS ?

Yes, I think you are right. It is a defect.

We surround the code by doAs() with the using of `ArcticTableOperations` or `ArcticHadoopTableOperations`, like 
```
public class ArcticTableOperations implements TableOperations {
...
  @Override
  public void commit(TableMetadata base, TableMetadata metadata) {
    arcticFileIO.doAs(() -> {
      ops.commit(base, metadata);
      return null;
    });
  }
...
}
```

However, like what you reported, when we call minor optimize commit in AMS, 
```
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:357) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:316) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseRewriteFiles.validate(BaseRewriteFiles.java:108) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:162) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:283) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:282) ~[iceberg-core-0.13.2.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.minorCommit(IcebergOptimizeCommit.java:165) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
```

`org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:162)` is not surrounded by doAs(), since the `TableOperations` is not used here.

I think it will work if we surrounded the code by doAs() when `IcebergOptimizeCommit.minorCommit` is invoked, like 
```
        arcticTable.io().doAs(() -> {
          dataFileRewrite.commit();
          return null;
        });
```

**Comment by wangtaohz** [comment]
> OptimizeQueueService.java:677
IcebergOptimizeCommit.java:165
TableOptimizeItem.java:426

@zhongqishang Are these three places the same Kerberos authentication failure? 
I think surrounding these code with `arcticTable.io().doAs()` will work. 

It would be appreciated if you could post a PR to fix this issue and test it in your environment.

**Comment by wangtaohz** [comment]
@zhoujinsong cc

**Comment by zhongqishang** [comment]
> @zhongqishang Are these three places the same Kerberos authentication failure? I think surrounding these code with `arcticTable.io().doAs()` will work.

After a simple verification it works.

> It would be appreciated if you could post a PR to fix this issue and test it in your environment.

I tested it in local to see if there are other places and will post a PR.
